//! Reusable fake process boundary: `FakeHarness`.
//!
//! Instead of each test inventing its own temporary shell script, a fake
//! executable is declared as a rule table:
//!
//! ```ignore
//! let claude = fake_harness::FakeHarness::new(&env.fake_bin, "claude")
//!     .version_line("9.9.9 (Fake Claude)")
//!     .on_prefix(["plugin", "list"], Action::stdout(r#"{"imports":[]}"#))
//!     .on_prefix(["mcp", "add"], Action::mcp_entry_mark(&state_dir))
//!     .build();
//! ```
//!
//! Every invocation is appended to a per-harness log inside the fake bin
//! directory; [`FakeHarness::invocations`] reads it back so tests can assert
//! which commands a workflow actually shelled out to (`assert_calls`-shaped
//! evidence) instead of trusting that a script "probably ran".
//!
//! Rule semantics: first matching rule wins (rules are matched in insertion
//! order); the fallback is `exit 0`. Scripts are POSIX `sh` — the same
//! mechanism the existing tests used, but centralized and self-describing.
//! On non-UNIX platforms the builder panics rather than silently producing a
//! script the test environment cannot execute.

use std::path::{Path, PathBuf};
use std::process::Command;

/// One rule's behavior when its pattern matches.
pub enum Action {
    /// Print `stdout` (with a trailing newline) and exit 0.
    Stdout(String),
    /// Exit with `code` and no output.
    Exit(i32),
    /// Raw POSIX `sh` lines inserted verbatim into the `case` arm (the
    /// escape hatch for vendor shapes too odd to model; the arm must end in
    /// `exit` or fall through to the case end).
    Script(String),
    /// Touch a marker file and exit 0.
    TouchFile(PathBuf),
    /// Simulate a vendor `mcp add` state transition: skip
    /// `--scope <x>`/`--transport <y>`/`--`, take the next token as the
    /// entry name, touch `<state_dir>/<name>`, exit 0.
    McpEntryMark(PathBuf),
    /// Simulate a vendor `plugin install <source>`: copy the source
    /// directory (argv position `arg_index`, 1-based shell position) into
    /// `<dest>/<basename>` and exit 0.
    CliPluginInstall { dest: PathBuf, arg_index: usize },
    /// The full vendor plugin-marketplace lifecycle as a state machine:
    /// `plugin marketplace add|list`, `plugin install|add <sel>`,
    /// `plugin list`, `plugin uninstall|remove <sel>`, with persisted
    /// state under `state_dir` (so install and inspection agree across
    /// separate `uze` invocations). Shape differs per vendor: Claude
    /// answers arrays of `{name, path}` / `{id, enabled}`, Codex answers
    /// `{marketplaces:[{name,root}]}` / `{installed:[{pluginId,...}]}`.
    VendorMarketplace {
        state_dir: PathBuf,
        vendor: MarketplaceVendor,
    },
    /// Hold the terminal the way an interactive agent session does: print
    /// `banner`, then echo back whatever is typed until `/exit`.
    ///
    /// A harness binary is two things — a CLI its vendor's verbs are run
    /// through, and a session that occupies a pane — and a stand-in that
    /// models only the first exits immediately when UZE launches it into a
    /// checkout, which is not what the real one does.
    InteractiveSession { banner: String },
    /// A conversation the harness names on disk before holding the terminal:
    /// `--session-id <id>` writes the transcript at
    /// `<transcripts_root>/<cwd flattened>/<id>.jsonl`, `--resume <id>`
    /// appends to the one already there.
    ///
    /// That file is the side effect UZE reads back — it is how a recorded
    /// conversation is proved to still exist, and how an agent that moved to
    /// another one is noticed — so a stand-in that only held the terminal
    /// would make every resume look like a conversation that had vanished.
    ConversationSession {
        transcripts_root: PathBuf,
        banner: String,
    },
    /// Antigravity's stub-install lifecycle: `plugin install <root>`
    /// stages a byte copy under `dest/<basename>` and `plugin list`
    /// answers `{"imports":[{"name":...}]}` from persisted state.
    VendorAgy { state_dir: PathBuf, dest: PathBuf },
}

/// The POSIX script a scripted agent runs — see
/// [`FakeHarness::scripted_agent`].
const SCRIPTED_AGENT: &str = r#"#!/bin/sh
# scripted agent generated by uze-testkit: plays the step script written
# for the checkout it was started in, then answers what is typed into its
# pane, the way a harness's prompt would take a message.
slot=$(basename "$PWD")
dir="${AGENT_SCRIPTS:?AGENT_SCRIPTS must name the scripts directory}"
log="$dir/$slot.log"
if [ -f "$dir/$slot.start.sh" ]; then
  sh "$dir/$slot.start.sh" >>"$log" 2>&1
fi
: > "$dir/$slot.started"
while IFS= read -r line; do
  printf '%s
' "$line" >> "$dir/$slot.inbox"
  case "$line" in
    *"rebase --continue"*)
      if [ -f "$dir/$slot.conflict.sh" ]; then
        sh "$dir/$slot.conflict.sh" >>"$log" 2>&1
      fi
      : > "$dir/$slot.resolved"
      ;;
    *"checks failed"*)
      if [ -f "$dir/$slot.gate.sh" ]; then
        sh "$dir/$slot.gate.sh" >>"$log" 2>&1
      fi
      : > "$dir/$slot.fixed"
      ;;
    *"Open a pull request"*|*"Open a merge request"*)
      if [ -f "$dir/$slot.request.sh" ]; then
        sh "$dir/$slot.request.sh" >>"$log" 2>&1
      fi
      : > "$dir/$slot.opened"
      ;;
    quit)
      exit 0
      ;;
  esac
done
"#;

/// What the Codex installer ends with: a question asked on `/dev/tty`,
/// whatever stdin is, answered by nobody when no one is watching. Every
/// stand-in's update verb and every installer the stand-in `curl` serves
/// asks it, so a provisioning step that leaves its child a terminal hangs.
const ASKS_ON_THE_TERMINAL: &str = r#"if ( : </dev/tty ) 2>/dev/null; then
  printf 'Start now? [y/N] ' >/dev/tty
  read -r answer </dev/tty
fi"#;

/// Vendor flavor for [`Action::VendorMarketplace`].
#[derive(Clone, Copy)]
pub enum MarketplaceVendor {
    Claude,
    Codex,
}

fn asks_on_the_terminal() -> Action {
    Action::Script(format!("{ASKS_ON_THE_TERMINAL}\nexit 0"))
}

impl Action {
    /// Convenience: `Stdout` from a string literal.
    pub fn stdout(text: impl Into<String>) -> Action {
        Action::Stdout(text.into())
    }
}

enum Pattern {
    /// Exact match of the full argv joined by spaces.
    Exact(String),
    /// Prefix match: argv starts with these tokens.
    Prefix(String),
    /// Special-case `--version` (the default behavior is a version echo).
    Version,
}

struct Rule {
    pattern: Pattern,
    action: Action,
}

/// Mutable rule-table builder; `.build()` materializes the executable.
pub struct FakeHarnessBuilder {
    name: String,
    bin_dir: PathBuf,
    invocations_dir: PathBuf,
    rules: Vec<Rule>,
    version_line: String,
}

impl FakeHarnessBuilder {
    /// `on` with an exact full-argv match.
    pub fn on(mut self, argv: impl AsRef<[&'static str]>, action: Action) -> Self {
        self.rules.push(Rule {
            pattern: Pattern::Exact(argv.as_ref().join(" ")),
            action,
        });
        self
    }

    /// `on_prefix` with a leading-token match (`["mcp", "add"]` matches
    /// `mcp add name -- cmd ...`).
    pub fn on_prefix(mut self, argv: impl AsRef<[&'static str]>, action: Action) -> Self {
        self.rules.push(Rule {
            pattern: Pattern::Prefix(argv.as_ref().join(" ")),
            action,
        });
        self
    }

    /// Overrides the `--version` answer (default: the harness name).
    pub fn version_line(mut self, line: impl Into<String>) -> Self {
        self.version_line = line.into();
        self
    }

    /// Writes the executable into `bin_dir` with mode 0o755 and returns the
    /// ready-to-assert handle.
    pub fn build(self) -> FakeHarness {
        unix_only(&self.name);

        let (script_path, log_path) = {
            let script_path = self.bin_dir.join(&self.name);
            let log_path = self.invocations_dir.join(format!("{}.log", self.name));
            (script_path, log_path)
        };

        let mut script = format!(
            "#!/bin/sh\n# fake harness '{}' generated by uze-testkit\n\
             echo \"$*\" >> '{}'\ncase \"$*\" in\n",
            self.name,
            log_path.display()
        );

        // `--version` echoes the declared line unless a rule claims it first.
        let version_rule = Rule {
            pattern: Pattern::Version,
            action: Action::stdout(self.version_line.clone()),
        };
        for rule in std::iter::once(version_rule).chain(self.rules) {
            match rule.pattern {
                Pattern::Version => {
                    script.push_str("  --version)\n");
                }
                Pattern::Exact(expected) => {
                    // Quotes are mandatory: the pattern is a single shell
                    // word (dash rejects space-separated words), and our
                    // argv joins tokens with spaces.
                    script.push_str(&format!("  \"{expected}\")\n"));
                }
                Pattern::Prefix(prefix) => {
                    // `"tokens"*)` — one shell word: quoted literals plus an
                    // UNQUOTED wildcard (dash treats a wholly-quoted `*` as
                    // a literal, which would never match).
                    script.push_str(&format!("  \"{prefix}\"*)\n"));
                }
            }
            script.push_str(&emit_action(&rule.action));
            script.push_str("  ;;\n");
        }

        script.push_str("esac\nexit 0\n");

        std::fs::write(&script_path, script).unwrap_or_else(|error| {
            panic!(
                "FakeHarness: failed to write {}: {error}",
                script_path.display()
            )
        });
        make_executable(&script_path);

        FakeHarness {
            name: self.name,
            script_path,
            invocations_dir: self.invocations_dir,
        }
    }
}

fn emit_action(action: &Action) -> String {
    match action {
        Action::Stdout(text) => format!("    echo '{}'\n    exit 0\n", text.replace('\'', "'\\''")),
        Action::Exit(code) => format!("    exit {code}\n"),
        Action::Script(lines) => {
            let mut block = String::new();
            for line in lines.lines() {
                block.push_str("    ");
                block.push_str(line);
                block.push('\n');
            }
            block
        }
        Action::TouchFile(path) => format!("    touch '{}'\n    exit 0\n", path.display()),
        Action::McpEntryMark(state_dir) => {
            let mut block = String::from("    shift 2\n");
            block.push_str("    name=\"\"\n");
            block.push_str("    while [ \"$#\" -gt 0 ]; do\n");
            block.push_str("      case \"$1\" in\n");
            block.push_str("        --scope|--transport) shift 2 ;;\n");
            block.push_str("        --) shift ; break ;;\n");
            block.push_str("        *) name=\"$1\" ; shift ;;\n");
            block.push_str("      esac\n");
            block.push_str("    done\n");
            block.push_str(&format!(
                "    [ -n \"$name\" ] && touch '{}/'\"$name\"\n",
                state_dir.display()
            ));
            block.push_str("    exit 0\n");
            block
        }
        Action::CliPluginInstall { dest, arg_index } => format!(
            "    plugin_dest='{}'\n    mkdir -p \"$plugin_dest\"\n    cp -R \"${}\" \"$plugin_dest/$(basename \"${}\")\" 2>/dev/null || true\n    exit 0\n",
            dest.display(),
            arg_index,
            arg_index
        ),
        Action::InteractiveSession { banner } => emit_interactive_session(banner),
        Action::ConversationSession {
            transcripts_root,
            banner,
        } => {
            // Claude Code's own naming: one directory per working
            // directory, every character that is not alphanumeric replaced
            // by a hyphen, one `.jsonl` per conversation named by its id.
            let mut block = format!(
                "    transcripts='{}'\n\
                 \x20   slug=$(printf '%s' \"$PWD\" | sed 's/[^A-Za-z0-9]/-/g')\n\
                 \x20   mkdir -p \"$transcripts/$slug\"\n\
                 \x20   printf '{{\"session\":\"%s\"}}\\n' \"$2\" >> \"$transcripts/$slug/$2.jsonl\"\n",
                transcripts_root.display()
            );
            block.push_str(&emit_interactive_session(banner));
            block
        }
        Action::VendorMarketplace { state_dir, vendor } => {
            emit_vendor_marketplace(state_dir, *vendor)
        }
        Action::VendorAgy { state_dir, dest } => emit_vendor_agy(state_dir, dest),
    }
}

/// The banner and the read loop an interactive stand-in holds its terminal
/// with. One copy: a session that also records its conversation differs
/// only in what it does before the prompt appears.
fn emit_interactive_session(banner: &str) -> String {
    format!(
        "    printf '%s\\n' '{banner}'\n\
         \x20   printf 'cwd %s\\n' \"$PWD\"\n\
         \x20   while IFS= read -r line; do\n\
         \x20     [ \"$line\" = '/exit' ] && exit 0\n\
         \x20     printf '> %s\\n' \"$line\"\n\
         \x20   done\n\
         \x20   exit 0\n"
    )
}

/// Generates the Antigravity stub-install state-machine script.
fn emit_vendor_agy(state_dir: &Path, dest: &Path) -> String {
    let mut block = String::new();
    block.push_str(&format!("    state_dir='{}'\n", state_dir.display()));
    block.push_str(&format!("    dest='{}'\n", dest.display()));
    block.push_str("    mkdir -p \"$state_dir\"\n");
    block.push_str("    case \"$*\" in\n");
    block.push_str("      \"plugin install\"*)\n");
    block.push_str("        root=\"$3\"\n");
    // The real `agy` stages a plugin under its manifest's `name`, not its
    // directory's: a generated plugin lives in `<name>--<market>/`.
    block.push_str(
        "        id=$(sed -n 's/^[[:space:]]*\"name\"[[:space:]]*:[[:space:]]*\"\\([^\"]*\\)\".*/\\1/p' \"$root/plugin.json\" 2>/dev/null | head -n 1)\n",
    );
    block.push_str("        [ -n \"$id\" ] || id=$(basename \"$root\")\n");
    block.push_str("        mkdir -p \"$dest\"\n");
    block.push_str("        cp -R \"$root\" \"$dest/$id\" 2>/dev/null || true\n");
    block.push_str("        printf '%s\\n' \"$id\" >> \"$state_dir/installed\"\n");
    block.push_str("        exit 0\n        ;;\n");
    block.push_str("      \"plugin list\"*)\n");
    block.push_str("        out=\"\"\n");
    block.push_str("        while IFS= read -r id; do\n");
    block.push_str("          out=\"$out{\\\"name\\\":\\\"$id\\\"},\"\n");
    block.push_str("        done < \"$state_dir/installed\" 2>/dev/null\n");
    block.push_str("        printf '{\"imports\":[%s]}' \"${out%,}\"\n");
    block.push_str("        exit 0\n        ;;\n");
    block.push_str("      \"plugin uninstall\"*)\n");
    block.push_str("        id=\"$3\"\n");
    block.push_str(&drop_installed_id("id"));
    block.push_str("        rm -rf \"$dest/$id\"\n");
    block.push_str("        exit 0\n        ;;\n");
    block.push_str("    esac\n");
    block
}

/// Shell that removes the line holding `$<variable>` from the persisted
/// list of installed ids.
///
/// `grep -vxF` rather than `sed -i`: BSD `sed` — which is macOS's `sed` —
/// reads whatever follows `-i` as the backup suffix, so the GNU spelling
/// silently consumes the script as a suffix and then treats the filename as
/// the script. The stand-in would answer "still installed" forever, and the
/// lifecycle tests would fail somewhere far from the cause. `-x -F` also
/// removes the reason the `sed` form needed a `\|...|` delimiter at all: a
/// package id containing `/` is a literal string here, never a pattern.
fn drop_installed_id(variable: &str) -> String {
    format!(
        "        if [ -n \"${variable}\" ] && [ -f \"$state_dir/installed\" ]; then\n\
         \x20         grep -vxF \"${variable}\" \"$state_dir/installed\" \
         > \"$state_dir/installed.new\"\n\
         \x20         mv \"$state_dir/installed.new\" \"$state_dir/installed\"\n\
         \x20       fi\n"
    )
}

/// Generates the vendored marketplace state-machine script for
/// [`Action::VendorMarketplace`].
fn emit_vendor_marketplace(state_dir: &Path, vendor: MarketplaceVendor) -> String {
    let state = format!("'{}'", state_dir.display());
    let mut block = String::new();
    block.push_str(&format!("    state_dir={state}\n"));
    block.push_str("    mkdir -p \"$state_dir\"\n");
    // `plugin marketplace add <root>`: remember root and marketplace name
    // (read out of the catalogue UZE itself wrote; default `uze-store`).
    block.push_str("    case \"$*\" in\n");
    block.push_str("      \"plugin marketplace add\"*)\n");
    block.push_str("        root=\"\"\n");
    block.push_str("        for arg in \"$@\"; do root=\"$arg\"; done\n");
    block.push_str("        printf '%s' \"$root\" > \"$state_dir/root\"\n");
    block.push_str(
        "        name=$(sed -n 's/.*\"name\" *: *\"\\([^\"]*\\)\".*/\\1/p' \"$root/marketplace.json\" \"$root/.claude-plugin/marketplace.json\" \"$root/.agents/plugins/marketplace.json\" 2>/dev/null | head -1)\n",
    );
    block.push_str("        [ -n \"$name\" ] || name=\"uze-store\"\n");
    block.push_str("        printf '%s' \"$name\" > \"$state_dir/name\"\n");
    block.push_str("        exit 0\n");
    block.push_str("        ;;\n");
    // `plugin install|add <selector>`: record the selector.
    block.push_str("      \"plugin install\"*|\"plugin add\"*)\n");
    block.push_str("        sel=\"$3\"\n");
    block.push_str(
        "        [ -n \"$sel\" ] && printf '%s\\n' \"$sel\" >> \"$state_dir/installed\"\n",
    );
    block.push_str("        id=\"${sel%%@*}\"\n");
    block.push_str("        root=$(cat \"$state_dir/root\" 2>/dev/null)\n");
    block.push_str("        [ -n \"$root\" ] && mkdir -p \"$root/$id\"\n");
    block.push_str("        exit 0\n");
    block.push_str("        ;;\n");
    match vendor {
        MarketplaceVendor::Claude => {
            block.push_str("      \"plugin marketplace list\"*)\n");
            block.push_str("        root=$(cat \"$state_dir/root\" 2>/dev/null)\n");
            block.push_str("        name=$(cat \"$state_dir/name\" 2>/dev/null)\n");
            block.push_str("        if [ -n \"$root\" ]; then\n");
            block.push_str(
                "          printf '[{\"name\":\"%s\",\"path\":\"%s\"}]' \"$name\" \"$root\"\n",
            );
            block.push_str("        else\n          printf '[]'\n        fi\n");
            block.push_str("        exit 0\n        ;;\n");
            block.push_str("      \"plugin list\"*)\n");
            block.push_str("        out=\"\"\n");
            block.push_str("        while IFS= read -r sel; do\n");
            block.push_str(
                "          entry=$(printf '{\"id\":\"%s\",\"enabled\":true}' \"$sel\")\n",
            );
            block.push_str("          out=\"$out$entry,\"\n");
            block.push_str("        done < \"$state_dir/installed\" 2>/dev/null\n");
            block.push_str("        printf '[%s]' \"${out%,}\"\n");
            block.push_str("        exit 0\n        ;;\n");
            block.push_str("      \"plugin uninstall\"*)\n");
            block.push_str("        sel=\"$3\"\n");
            block.push_str(&drop_installed_id("sel"));
            block.push_str("        exit 0\n        ;;\n");
        }
        MarketplaceVendor::Codex => {
            block.push_str("      \"plugin marketplace list\"*)\n");
            block.push_str("        root=$(cat \"$state_dir/root\" 2>/dev/null)\n");
            block.push_str("        name=$(cat \"$state_dir/name\" 2>/dev/null)\n");
            block.push_str("        if [ -n \"$root\" ]; then\n");
            block.push_str(
                "          printf '{\"marketplaces\":[{\"name\":\"%s\",\"root\":\"%s\"}]}' \"$name\" \"$root\"\n",
            );
            block.push_str("        else\n          printf '{\"marketplaces\":[]}'\n        fi\n");
            block.push_str("        exit 0\n        ;;\n");
            block.push_str("      \"plugin list\"*)\n");
            block.push_str("        out=\"\"\n");
            block.push_str("        root=$(cat \"$state_dir/root\" 2>/dev/null)\n");
            block.push_str("        name=$(cat \"$state_dir/name\" 2>/dev/null)\n");
            block.push_str("        while IFS= read -r sel; do\n");
            // `sel` is the vendor selector `{active_name}@{native
            // marketplace}` (ADR-036: `active_name` is bare, never
            // marketplace-qualified). The real Codex resolves an install by
            // looking up `active_name` in its own catalogue and reporting
            // back that entry's `source.path` — the generated dir named by
            // the qualified `{plugin}@{marketplace}` id (see
            // `codex::generate::generated_catalogue_document`), which has no
            // fixed relationship to `active_name` any more (an alias can
            // make them differ). Do the same lookup here, against the exact
            // catalogue UZE wrote, instead of deriving the path from the
            // selector's shape.
            block.push_str("          active=\"${sel%%@*}\"\n");
            block.push_str("          catalog=\"$root/.agents/plugins/marketplace.json\"\n");
            block.push_str(
                "          nameline=$(grep -n \"\\\"name\\\": *\\\"$active\\\"\" \"$catalog\" 2>/dev/null | head -1 | cut -d: -f1)\n",
            );
            block.push_str("          relpath=\"\"\n");
            block.push_str("          if [ -n \"$nameline\" ]; then\n");
            block.push_str(
                "            relpath=$(tail -n \"+$nameline\" \"$catalog\" | sed -n 's/.*\"path\" *: *\"\\([^\"]*\\)\".*/\\1/p' | head -1)\n",
            );
            block.push_str("          fi\n");
            block.push_str("          relpath=\"${relpath#./}\"\n");
            block.push_str("          entry=$(printf '{\"pluginId\":\"%s\",\"enabled\":true,\"installed\":true,\"marketplaceName\":\"%s\",\"path\":\"%s/%s\"}' \"$sel\" \"$name\" \"$root\" \"$relpath\")\n");
            block.push_str("          out=\"$out$entry,\"\n");
            block.push_str("        done < \"$state_dir/installed\" 2>/dev/null\n");
            block.push_str("        printf '{\"installed\":[%s]}' \"${out%,}\"\n");
            block.push_str("        exit 0\n        ;;\n");
            block.push_str("      \"plugin remove\"*)\n");
            block.push_str("        sel=\"$3\"\n");
            block.push_str(&drop_installed_id("sel"));
            block.push_str("        exit 0\n        ;;\n");
        }
    }
    block.push_str("    esac\n");
    block
}

/// Materialized fake executable plus its invocation log.
pub struct FakeHarness {
    name: String,
    script_path: PathBuf,
    invocations_dir: PathBuf,
}

impl FakeHarness {
    /// A builder for a fake executable named `name` inside `bin_dir` (see
    /// [`FakeHarness::build`] — the builder's `new` is the entry point; the
    /// materialized handle comes from `.build()`).
    #[allow(clippy::new_ret_no_self)] // the fluent builder shape is the point
    pub fn new(bin_dir: &Path, name: &str) -> FakeHarnessBuilder {
        std::fs::create_dir_all(bin_dir).expect("FakeHarness: bin dir must be creatable");
        std::fs::create_dir_all(bin_dir.join(".invocations"))
            .expect("FakeHarness: invocation log dir must be creatable");
        FakeHarnessBuilder {
            name: name.to_owned(),
            bin_dir: bin_dir.to_path_buf(),
            invocations_dir: bin_dir.join(".invocations"),
            rules: Vec::new(),
            version_line: format!("{name} fake 0.0.0"),
        }
    }

    /// The executable path (for `PATH`-based resolution checks).
    /// A long-lived, interactive fake agent: started in a checkout, it runs
    /// `<scripts_dir>/<checkout name>.start.sh` when present, touches
    /// `<checkout name>.started`, then reads its pane line by line — a line
    /// mentioning `rebase --continue` runs `<checkout name>.conflict.sh` and
    /// touches `.resolved`; one asking it to open a pull request runs
    /// `.request.sh` and touches `.opened`; one mentioning `checks failed`
    /// runs `.gate.sh`
    /// and touches `.fixed`; `quit` exits. Every line lands in `.inbox`.
    /// `AGENT_SCRIPTS` must name `scripts_dir` in the agent's environment.
    ///
    /// What a model would do, made deterministic: an engine test scripts
    /// the commits an agent makes and how it answers a message, and asserts
    /// on Git instead of on a transcript.
    pub fn scripted_agent(bin_dir: &Path, name: &str) -> FakeHarness {
        unix_only(name);
        let invocations_dir = bin_dir.join(".invocations");
        std::fs::create_dir_all(&invocations_dir).unwrap_or_else(|error| {
            panic!(
                "FakeHarness: failed to create {}: {error}",
                invocations_dir.display()
            )
        });
        let script_path = bin_dir.join(name);
        std::fs::write(&script_path, SCRIPTED_AGENT).unwrap_or_else(|error| {
            panic!(
                "FakeHarness: failed to write {}: {error}",
                script_path.display()
            )
        });
        make_executable(&script_path);
        FakeHarness {
            name: name.to_owned(),
            script_path,
            invocations_dir,
        }
    }

    pub fn path(&self) -> PathBuf {
        self.script_path.clone()
    }

    /// A `Command` that spawns this fake with the caller-supplied args.
    pub fn command(&self) -> Command {
        Command::new(&self.script_path)
    }

    /// Parsed invocation log: one entry per call, tokens split on
    /// whitespace. Empty when nothing was invoked.
    pub fn invocations(&self) -> Vec<Vec<String>> {
        let log = self.invocations_dir.join(format!("{}.log", self.name));
        match std::fs::read_to_string(&log) {
            Ok(contents) => contents
                .lines()
                .map(|line| line.split_whitespace().map(str::to_owned).collect())
                .collect(),
            Err(_) => Vec::new(),
        }
    }

    /// True when some invocation starts with `argv`.
    pub fn was_called_with_prefix(&self, argv: &[&str]) -> bool {
        self.invocations().iter().any(|call| {
            call.len() >= argv.len()
                && call
                    .iter()
                    .zip(argv.iter())
                    .all(|(actual, expected)| actual == expected)
        })
    }
}

// ============================================================================
// The standard set — one composition, every consumer.
// ============================================================================

/// The stand-ins a test or a journey needs to exercise UZE's delivery against
/// every harness the product knows.
///
/// This composition lives here, and not in whichever suite happens to need it
/// first, because a second stand-in for the same vendor drifting from the
/// first is a way for two tiers to disagree about what a harness does while
/// both stay green — the failure they exist to catch.
///
/// What a stand-in emulates is only ever the side effect UZE *reads back*.
/// Where a harness merely has to exit zero, it exits zero. Real vendor
/// behaviour is the conformance Lab's verdict — it runs the actual binary
/// against a synthetic provider — never this file's.
pub struct Standard<'a> {
    /// Where the executables are written; belongs at the head of `PATH`.
    pub bin_dir: &'a Path,
    /// The HOME the stand-ins write their vendor state under.
    pub home: &'a Path,
    /// Where each stand-in keeps the state that makes its own invocations
    /// agree with each other across separate `uze` runs.
    pub state_root: &'a Path,
    /// Whether a bare invocation holds the terminal the way an interactive
    /// agent session does. A journey launches these into panes and gates on
    /// the banner; a CLI-only suite does not need it and pays nothing for
    /// leaving it off.
    pub interactive: bool,
    /// The name OpenCode's binary is installed under. `opencode` is what a
    /// current install produces; the acceptance suite pins `opencode2` on
    /// purpose, because that legacy v2 name is a path UZE still probes
    /// (`opencode/provision.rs`).
    pub opencode_binary: &'a str,
}

impl Standard<'_> {
    /// Writes every stand-in and returns them in registration order.
    pub fn install(&self) -> Vec<FakeHarness> {
        self.install_installer_fetcher();
        let session = |display: &str, version: &str| Action::InteractiveSession {
            banner: format!("{display} {version}"),
        };
        vec![
            self.interactive(
                self.conversational(
                    FakeHarness::new(self.bin_dir, "claude")
                        .version_line("9.9.9 (Fake Claude)")
                        .on(["update"], asks_on_the_terminal())
                        .on_prefix(
                            ["plugin"],
                            Action::VendorMarketplace {
                                state_dir: self.state_root.join("claude"),
                                vendor: MarketplaceVendor::Claude,
                            },
                        ),
                    self.home.join(".claude/projects"),
                    "Claude Code v9.9.9 (fake)",
                ),
                session("Claude Code", "v9.9.9 (fake)"),
            )
            .build(),
            self.interactive(
                FakeHarness::new(self.bin_dir, "codex")
                    .version_line("codex-cli 9.9.9")
                    .on(["update"], asks_on_the_terminal())
                    .on_prefix(
                        ["plugin"],
                        Action::VendorMarketplace {
                            state_dir: self.state_root.join("codex"),
                            vendor: MarketplaceVendor::Codex,
                        },
                    ),
                session("Codex", "v9.9.9 (fake)"),
            )
            .build(),
            self.interactive(
                FakeHarness::new(self.bin_dir, self.opencode_binary)
                    .version_line("opencode2 v9.9.9")
                    .on(["upgrade"], asks_on_the_terminal()),
                session("OpenCode", "v9.9.9 (fake)"),
            )
            .build(),
            self.interactive(
                // A bare token, because that is what `agy --version` prints
                // (`1.1.19` in dogfood — see antigravity/provision.rs). A
                // stand-in that answered `agy 9.9.9` made UZE record the
                // version as `agy`, which is what its first-token parse is
                // right to do and what the real vendor never produces.
                FakeHarness::new(self.bin_dir, "agy")
                    .version_line("9.9.9")
                    .on(["update"], asks_on_the_terminal())
                    .on_prefix(
                        ["plugin"],
                        Action::VendorAgy {
                            state_dir: self.state_root.join("agy"),
                            dest: self.home.join(".gemini/config/plugins"),
                        },
                    ),
                session("Antigravity CLI", "v9.9.9 (fake)"),
            )
            .build(),
        ]
    }

    /// A `curl` that fetches an installer which only asks its question.
    ///
    /// OpenCode's provisioning route for the legacy `opencode2` name is
    /// `sh -c "curl -fsSL https://opencode.ai/v2/install | bash"`, and a
    /// suite that pins that name to keep the path proven was reaching the
    /// public Internet to do it — the run failed whenever the network was
    /// down, and piped a remote script into `bash` when it was up. A
    /// stand-in first on `$PATH` answers offline and exits zero, so UZE
    /// still runs the command it would really run; the invocation log is
    /// what proves it did.
    ///
    /// Not returned with the harnesses: callers print that list as the set
    /// of harness stand-ins, and this is not one.
    fn install_installer_fetcher(&self) {
        FakeHarness::new(self.bin_dir, "curl")
            .version_line("curl 9.9.9 (fake)")
            .on_prefix(["-fsSL"], Action::stdout(ASKS_ON_THE_TERMINAL))
            .build();
    }

    /// Attaches the bare-invocation session rule, when this set is
    /// interactive. Last, so every vendor verb above still claims its own
    /// argv first.
    fn interactive(&self, builder: FakeHarnessBuilder, action: Action) -> FakeHarnessBuilder {
        if self.interactive {
            builder.on([""], action)
        } else {
            builder
        }
    }

    /// Attaches the two session arguments a harness that lets its
    /// conversation be named answers to. Only where the set is interactive:
    /// off it, nothing launches one of these into a pane, and a stand-in
    /// that recorded a conversation nobody was in would be state with no
    /// reader.
    fn conversational(
        &self,
        builder: FakeHarnessBuilder,
        transcripts_root: PathBuf,
        banner: &str,
    ) -> FakeHarnessBuilder {
        if !self.interactive {
            return builder;
        }
        let conversation = || Action::ConversationSession {
            transcripts_root: transcripts_root.clone(),
            banner: banner.to_owned(),
        };
        builder
            .on_prefix(["--session-id"], conversation())
            .on_prefix(["--resume"], conversation())
    }
}

#[cfg(unix)]
fn make_executable(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))
        .unwrap_or_else(|error| panic!("FakeHarness: failed to chmod {}: {error}", path.display()));
}

#[cfg(not(unix))]
fn make_executable(_path: &Path) {}

/// The fakes are POSIX `sh` scripts until they dispatch through
/// `uze-fake-harness`; on any other platform a test reaching one fails here
/// with the reason, rather than on a script nothing can run.
fn unix_only(name: &str) {
    #[cfg(not(unix))]
    panic!("FakeHarness generates POSIX sh scripts; supported on Unix only ({name})");
    #[cfg(unix)]
    let _ = name;
}
